VM_NAME= "ubuntu1804-workstation-#{SecureRandom.hex(2)}"
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu1804-workstation" do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "#{VM_NAME}"
    config.vm.boot_timeout = 600
    config.vm.network :private_network, ip: "10.0.0.20"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../ansible/playbooks/linux_workstation.yml"
        ansible.config_file = "../../ansible/ansible.cfg"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME}" 
      vb.customize ["modifyvm", :id, "--memory", 1000]
      vb.customize ["modifyvm", :id, "--cpus", 1]
    end
  end
end
