variable "vpc_security_group_ids" {}
variable "ec2_subnet_id" {}
variable "general" {}
variable "aws" {}
variable "windows_servers" {}
variable "windows_server_instances" {}
variable "linux_servers" {}
variable "linux_server_instances" {}
variable "splunk_server" {}
variable "snort_server" {}
