#!/bin/bash
#
# clamav-cron v. 0.6 - Copyright © 2009, Stefano Stagnaro
# This is Free Software released under the GNU GPL license version 3

#============================================#
#        User configuration section          #
#============================================#

# Log file name and its path:
CV_LOGFILE="/var/log/clamav/clamav-cron.log"

# Notification e-mail sender (could be fake):
CV_MAILFROM=""

# Notification e-mail recipient:
CV_MAILTO=""

# Notification e-mail secondary recipients:
#CV_MAILTO_CC="stefano@abc.com; danilo@abc.com"

# Notification e-mail subject:
CV_SUBJECT="conan - ClamAV scan report"

#============================================#

CV_TARGET="$1"
CV_VERSION="0.6"

if [ -e $CV_LOGFILE ]
then
	/bin/rm $CV_LOGFILE
fi

CV_TARGET="/"
#if [ -z "$1" ]
#then
#	CV_TARGET="$HOME"
#fi

#To be read on stdout (and root mail):
echo -e `basename $0` v. $CV_VERSION - Copyright 2009, Stefano Stagnaro '\n'

#To be read on logfile (sent via sendmail):
echo -e $CV_SUBJECT - $(date) '\n' >> $CV_LOGFILE
echo -e Script: `basename $0` v. $CV_VERSION - Copyright 2009, Stefano Stagnaro  >> $CV_LOGFILE
echo -e Scanned: $CV_TARGET on $HOSTNAME'\n' >> $CV_LOGFILE
#/usr/bin/freshclam --log=$CV_LOGFILE --user root --verbose
#To be read on stdout (and root mail):
echo -e '------------------------------------\n'

/usr/bin/clamscan --infected --log=$CV_LOGFILE --recursive $CV_TARGET --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/media --exclude=/mnt --exclude=/usr/share/doc/clamav-0.94.2/test --exclude=/home/drac0/container/seafile-data/blocks
CLAMSCAN=$?

if [ "$CLAMSCAN" -eq "1" ]
then
	CV_SUBJECT="[VIRUS!] "$CV_SUBJECT
elif [ "$CLAMSCAN" -gt "1" ]
then
	CV_SUBJECT="[ERR] "$CV_SUBJECT
fi

#/usr/bin/mail -s "$CV_SUBJECT" $CV_MAILTO -- -f $CV_MAILFROM < $CV_LOGFILE
