Vagrant.configure("2") do |config| 
 
config.vm.define "attack-range-windows-server-0" do |config|
    config.vm.box = "d1vious/windows2016"
    config.vm.hostname = "ar-win"
    config.vm.boot_timeout = 600
    config.vm.communicator = "winrm"
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true
    config.winrm.timeout = 300
    config.winrm.retry_limit = 20
    config.vm.network "forwarded_port", guest: 5985, host: 5985
    config.vm.network :private_network, ip: "10.0.1.14"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  
    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          ansible_port: 6001,
          ansible_winrm_scheme: 'http',
          splunk_admin_password: 'Pl3ase-k1Ll-me:p',
          splunk_uf_win_url: 'https://download.splunk.com/products/universalforwarder/releases/8.2.5/windows/splunkforwarder-8.2.5-77015bc7a462-x64-release.msi',
          win_password: 'Pl3ase-k1Ll-me:p'
        }
        ansible.playbook = "../packer/ansible/windows.yml"
        ansible.compatibility_mode = "2.0"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          ansible_port: 6001,
          ansible_winrm_scheme: 'http',
          attack_range_password: "ChangeMe123!1",
          cloud_provider: "local",
          key_name: "ar",
          attack_range_name: "ar",
          ip_whitelist: "0.0.0.0/0",
          version: "3.0.0",
          hostname: "ar-win",
          image: "windows-2016-v3-0-0",
          create_domain: "0",
          join_domain: "0",
          win_sysmon_config: "SwiftOnSecurity.xml",
          install_red_team_tools: "0",
          atomic_red_team_repo: "redcanaryco",
          atomic_red_team_branch: "master",
          prelude: "0",
          prelude_operator_url: "https://download.prelude.org/latest?arch=x64&platform=linux&variant=zip&edition=headless",
          prelude_account_email: "test@test.com",
        }
        ansible.playbook = "../terraform/ansible/windows_post.yml"
        ansible.compatibility_mode = "2.0"
    end
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "ar-win"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end


end