Vagrant.configure("2") do |config| 
 
config.vm.define "attack-range-splunk-server" do |config|
  VM_NAME= "attack-range-splunk-server"
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "#{VM_NAME}"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 8000, host: 8000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8089, host: 8089, protocol: "tcp"
  config.vm.network :private_network, ip: "10.0.1.5"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/splunk_server.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3",
        splunk_admin_password: 'I-l1ke-Attack-Range!',
        splunk_url: 'https://www.splunk.com/page/download_track?file=7.3.2/linux/splunk-7.3.2-c60db69f8e32-Linux-x86_64.tgz&ac=&wget=true&name=wget&platform=Linux&architecture=x86_64&version=7.3.2&product=splunk&typed=release',
        splunk_binary: 'splunk-7.3.2-c60db69f8e32-Linux-x86_64.tgz',
        s3_bucket_url: 'https://attack-range-appbinaries.s3-us-west-2.amazonaws.com',
        splunk_escu_app: 'DA-ESS-ContentUpdate-latest.tar.gz',
        splunk_asx_app: 'Splunk_Analytic_Story_Execution-latest.tar.gz',
        splunk_windows_ta: 'splunk-add-on-for-microsoft-windows_700.tgz',
        splunk_cim_app: 'splunk-common-information-model-cim_4130.tgz',
        splunk_sysmon_ta: 'add-on-for-microsoft-sysmon_810.tgz'
      }
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME}"
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end
end


config.vm.define "attack-range-domain-controller" do |config|
  VM_NAME_WIN_DC= "attack-range-domain-controller"
  config.vm.box = "d1vious/windows2016"
  config.vm.hostname = "dc"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 6000
  config.vm.network :private_network, ip: "10.0.1.6"

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 6000,
        ansible_winrm_scheme: 'http',
        splunk_indexer_ip: "10.0.1.5",
        win_password: 'I-l1ke-Attack-Range!',
        splunk_uf_win_url: 'https://www.splunk.com/page/download_track?file=7.3.2/windows/splunkforwarder-7.3.2-c60db69f8e32-x64-release.msi&ac=&wget=true&name=wget&platform=Windows&architecture=x86_64&version=7.3.2&product=universalforwarder&typed=release',
        win_sysmon_url: 'https://download.sysinternals.com/files/Sysmon.zip',
        win_sysmon_template: 'SysmonConfig-TSwift.xml',
        splunk_admin_password: 'I-l1ke-Attack-Range!'
      }
      ansible.playbook = "../ansible/playbooks/windows_dc.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME_WIN_DC}"
    vb.default_nic_type = "82545EM"
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 1]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end

config.vm.define "attack-range-win10" do |config|
  VM_NAME_WIN= "attack-range-win10"
  config.vm.box = "d1vious/windows10"
  config.vm.hostname = "win10"
  config.vm.boot_timeout = 600
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.winrm.retry_limit = 20
  config.vm.network "forwarded_port", guest: 5985, host: 5985
  config.vm.network :private_network, ip: "10.0.1.9"

  config.vm.provision "ansible" do |ansible|
      ansible.extra_vars = {
        ansible_port: 5985,
        splunk_indexer_ip: "10.0.1.5",
        win_password: 'I-l1ke-Attack-Range!',
        splunk_uf_win_url: 'https://www.splunk.com/page/download_track?file=7.3.2/windows/splunkforwarder-7.3.2-c60db69f8e32-x64-release.msi&ac=&wget=true&name=wget&platform=Windows&architecture=x86_64&version=7.3.2&product=universalforwarder&typed=release',
        win_sysmon_url: 'https://download.sysinternals.com/files/Sysmon.zip',
        win_sysmon_template: 'SysmonConfig-TSwift.xml',
        splunk_admin_password: 'I-l1ke-Attack-Range!',
        windows_server_join_domain: '1',
        windows_domain_controller_private_ip: '10.0.1.6'
      }
      ansible.playbook = "../ansible/playbooks/windows_workstation.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME_WIN}"
    vb.default_nic_type = "82545EM"
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 1]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end


end