config.vm.define "ar-phantom-{{config.general.key_name}}-{{config.general.attack_range_name}}" do |config|
    VM_NAME_P= "ar-phantom"
    config.vm.box = "bento/centos-7"
    config.vm.hostname = "#{VM_NAME_P}"
    config.vm.boot_timeout = 600
    config.vm.network "forwarded_port", guest: 443, host: 8443, protocol: "tcp"
    config.vm.network :private_network, ip: "192.168.56.13"
  
    # Add this line near the top of the config block
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../terraform/ansible/phantom_server.yml"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          use_prebuilt_images_with_packer: '0',
{% for key, value in config.general.items() %}
          general.{{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in config.splunk_server.items() %}
          splunk_server.{{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in config.phantom_server.items() %}
          phantom_server.{{ key }}: "{{ value }}",
{% endfor %}
        }
    end
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_P}"
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
  end