
config.vm.define "attack-range-kali" do |config|
    VM_NAME_KALI= "attack-range-kali"
    config.vm.box = "kalilinux/rolling"
    config.vm.boot_timeout = 600
    config.vm.hostname = "kali"
    config.vm.network :private_network, ip: "10.0.1.30"
    config.ssh.password = "vagrant"
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_KALI}"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end