"""
author: Teoderick Contreras
email: tccontreras@splunk.com
description: a simple attack range utility tool designed to replay attack data via several category:
 - analytic story
 - detection name
 - detection guid id
 - Mitre attack Technique ID
"""

import typer
import os
import sys
import yaml
from rich.live import Live
from rich.layout import Layout
from rich.panel import Panel
from time import sleep
import uuid
from colorama import Fore, Back, Style, init
from utility.color_print import ColorPrint

from utility.utility_helper import UtilityHelper


def main():
     
    uh = UtilityHelper()

    uh.clear_screen()

    uh.show_banner()

    app = typer.Typer()

    @app.command()
    def input_helps(
        detection_name: str = typer.Option(None, "--name", "-n", 
                                                       help="comma-separated list of security content detection name.\n\n <e.g. python3 total_replay.py -n '7zip CommandLine To SMB Share Path, CMLUA Or CMSTPLUA UAC Bypass'>"), 
        technique_id: str = typer.Option(None, "--technique_id", "-tid", 
                                         help="comma-separated list of security content detection mitre technique id.\n\n <e.g. python3 total_replay.py -tid 'T1021, T1020, T1537'>"),            
        guid: str = typer.Option(None, "--guid", "-g",
                                 help="comma-separated list of security content detection guid.\n\n <e.g. python3 total_replay.py -g '01d29b48-ff6f-11eb-b81e-acde48001123, 004e32e2-146d-11ec-a83f-acde48001122'>"),
        analytic_story: str = typer.Option(None, "--analytic_story", "-as",
                                           help="comma-separated list of security content analytic story.\n\n <e.g. python3 total_replay.py -as 'AgentTesla, Remcos, Snake Malware, AcidPour'>"),
        local_data_path: str = typer.Option(None, "--local_data_path", "-ld", 
                                            help="directory path of the cache directory generated by echo-attack during download of logs.\n\n <e.g. python3 total_replay.py -ld '~\\home\\replayed_yaml_cache'>"),
        
        file_detection_name: str = typer.Option(None, "--file_detection_name", "-fn", 
                                                 help="file path that contains security content detection names.\n\n <e.g. python3 total_replay.py -fn '~\\home\\detection_name_list.txt'>"),
        file_detection_tid: str = typer.Option(None, "--file_detection_tid", "-ftid", 
                                               help="file path that contains security content detection mitre technique id.\n\n <e.g. python3 total_replay.py -ftid '~\\home\\detection_tid_list.txt'>"),
        file_detection_guid: str = typer.Option(None, "--file_detection_guid", "-fg", 
                                                help="file path that contains security content detection guid.\n\n <e.g. python3 total_replay.py -fg '~\\home\\detection_guid_list.txt'>"),
        file_detection_analytic_story: str = typer.Option(None, "--file_detection_analytic_story", "-fas", 
                                                          help="file path that contains security content detection analytic story.\n\n <e.g. python3 total_replay.py -fas '~\\home\\detection_analytic_story_list.txt'>"),
        file_detection_greedy: str = typer.Option(None, "--file_detection_greedy", "-fgr", 
                                                          help="file path that contains security content detection analytic story, technique ID, guid and detection name.\n\n <e.g. python3 total_replay.py -fgr '~\\home\\detection_analytic_story_list.txt'>"),
        index_value: str = typer.Option("test", "--index", "-i", 
                                  help="Index to replay the attack data. Set this first if you want to use a different index.\n\n <python3 total_replay.py -i test -tid 'T1071, T1059'>", hidden=True),
    ):
        


        ### via console
        if detection_name:
            ColorPrint.print_yellow_fg("[+][. INFO]: Searching For both Security Content Detection Name and .YML Filename ...")
            normalized_list_args = uh.normalized_args_tolist(detection_name)
            generated_guid = uuid.uuid4()
            marker_uid = "detection_name_replay_" + str(generated_guid)
            uh.process_replay_attack_data_by_file_name("file_name", normalized_list_args, index_value, marker_uid)
            uh.process_replay_attack_data("name", normalized_list_args, index_value, marker_uid)

        elif guid:
            ColorPrint.print_yellow_fg("[+][. INFO]: Searching For Security Content Detection GUID ...")
            normalized_list_args = uh.normalized_args_tolist(guid)
            generated_guid = uuid.uuid4()
            marker_uid = "guid_replay_" + str(generated_guid)
            uh.process_replay_attack_data("id", normalized_list_args, index_value, marker_uid)

        elif technique_id:
            ColorPrint.print_yellow_fg("[+][. INFO]: Searching For Security Content Detection Mitre ATT&CK Technique ID ...")
            normalized_list_args = uh.normalized_args_tolist(technique_id)
            generated_guid = uuid.uuid4()
            marker_uid = "technique_id_replay_" + str(generated_guid)
            uh.process_replay_attack_data("mitre_attack_id", normalized_list_args, index_value, marker_uid)

        elif analytic_story:
            ColorPrint.print_yellow_fg("[+][. INFO]: Searching For Security Content Analytic Story ...")
            normalized_list_args = uh.normalized_args_tolist(analytic_story)
            generated_guid = uuid.uuid4()
            marker_uid = "analytic_story_replay_" + str(generated_guid)
            uh.process_replay_attack_data("analytic_story", normalized_list_args, index_value, marker_uid)

        ### by file input
        elif file_detection_name:
            segregate = uh.normalized_file_args(file_detection_name)
            generated_guid = uuid.uuid4()
            marker_uid = "file_detection_name_replay_" + str(generated_guid)

            if "detection_filename" in segregate:
                normalized_list_args = segregate['detection_filename']
                uh.process_replay_attack_data_by_file_name("file_name", normalized_list_args, index_value, marker_uid)
            
            if "detection_and_analytic_story_name" in segregate:
                normalized_list_args = segregate['detection_and_analytic_story_name']
                uh.process_replay_attack_data("name", normalized_list_args, index_value, marker_uid)

        elif file_detection_tid:
            segregate = uh.normalized_file_args(file_detection_tid)
            
            if "mitre_attack_tid" in segregate:
                normalized_list_args = segregate['mitre_attack_tid'] 
                generated_guid = uuid.uuid4()
                marker_uid = "file_detection_tid_replay_" + str(generated_guid)
                uh.process_replay_attack_data("mitre_attack_id", normalized_list_args, index_value, marker_uid)

        elif file_detection_guid:
            segregate = uh.normalized_file_args(file_detection_guid)

            if "guid" in segregate:
                normalized_list_args = segregate['guid']             
                generated_guid = uuid.uuid4()
                marker_uid = "file_detection_guid_replay_" + str(generated_guid)
                uh.process_replay_attack_data("id", normalized_list_args, index_value, marker_uid)

        elif file_detection_analytic_story:
            
            segregate = uh.normalized_file_args(file_detection_analytic_story)

            if "detection_and_analytic_story_name" in segregate:
                normalized_list_args = segregate['detection_and_analytic_story_name']
                generated_guid = uuid.uuid4()
                marker_uid = "file_detection_analytic_story_replay_" + str(generated_guid)
                uh.process_replay_attack_data("analytic_story", normalized_list_args, index_value, marker_uid)

        elif file_detection_greedy:
            segregate = uh.normalized_file_args(file_detection_greedy)
            generated_guid = uuid.uuid4()
            marker_uid = "file_detection_greedy_replay_" + str(generated_guid)
            
            if "detection_filename" in segregate:
                ColorPrint.print_info_fg("[+] greedy replay... [detection_filename]")
                normalized_list_args = segregate['detection_filename']
                uh.process_replay_attack_data_by_file_name("file_name", normalized_list_args, index_value, marker_uid)
            
            if "detection_and_analytic_story_name" in segregate:
                ColorPrint.print_info_fg("[+] greedy replay... [detection_and_analytic_story_name]")
                normalized_list_args = segregate['detection_and_analytic_story_name']
                uh.process_replay_attack_data("name", normalized_list_args, index_value, marker_uid)
                uh.process_replay_attack_data("analytic_story", normalized_list_args, index_value, marker_uid)

            if "mitre_attack_id" in segregate:
                ColorPrint.print_info_fg("[+] greedy replay... [mitre_attack_id]")
                normalized_list_args = segregate['mitre_attack_id']            
                uh.process_replay_attack_data("mitre_attack_id", normalized_list_args, index_value, marker_uid)

            if "guid" in segregate:
                ColorPrint.print_info_fg("[+] greedy replay... [mitre_attack_id]")
                normalized_list_args = segregate['guid']  
                uh.process_replay_attack_data("id", normalized_list_args, index_value, marker_uid)


        elif local_data_path:
            uh.process_local_yaml_cache(local_data_path, index_value)


        else:
            ColorPrint.print_error_fg("[+] [STATUS]: [ERROR] invalid inputs\n")

        ColorPrint.print_success_fg("Thank you... <(^_^)>")    
        
    app()

    


    return



if __name__ == "__main__":
    main()