---

- name: Check if {{ item }} exists
  stat:
    path: /opt/splunk/etc/apps/{{ item }}
  register: app_exists

- name: download {{ item }} from S3 bucket
  get_url:
    url: '{{ s3_bucket_url }}/{{ item }}'
    dest: /tmp/{{ item }}.tgz
  when: app_exists.stat.exists == False

- name: Install {{ item }} via REST
  uri:
    url: "https://127.0.0.1:8089/services/apps/local"
    method: POST
    user: "admin"
    password: "{{ splunk_admin_password }}"
    validate_certs: false
    body: "name=/tmp/{{ item }}.tgz&update=true&filename=true"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 60
  when: app_exists.stat.exists == False
  notify: restart splunk
