config.vm.define "attack-range-splunk-server-{{ count }}" do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "{{ server.hostname }}"
    config.vm.boot_timeout = 600
    config.vm.network :private_network, ip: "10.0.1.{{21 + count}}"
  
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../packer/ansible/linux_server.yml"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_python_interpreter: "/usr/bin/python3",
          splunk_admin_password: 'Pl3ase-k1Ll-me:p',
          splunk_uf_url: 'https://download.splunk.com/products/universalforwarder/releases/8.2.5/linux/splunkforwarder-8.2.5-77015bc7a462-linux-2.6-amd64.deb'
        }
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../terraform/ansible/linux_server_post.yml"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_python_interpreter: "/usr/bin/python3",  
{% for key, value in config.general.items() %}
          {{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in server.items() %}
          {{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in config.simulation.items() %}
          {{ key }}: "{{ value }}",
{% endfor %}
        }
    end
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "{{ server.hostname }}"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end