config.vm.define "ar-linux-{{config.general.key_name}}-{{config.general.attack_range_name}}-{{count}}" do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "{{ server.hostname }}"
    config.vm.boot_timeout = 600
    config.vm.network :private_network, ip: "192.168.56.{{21 + count}}"
    config.vm.network "forwarded_port", guest: 22, host: {{ 2022 + count }}
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../terraform/ansible/linux_server.yml"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_python_interpreter: "/usr/bin/python3",  
{% for key, value in config.general.items() %}
          general.{{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in server.items() %}
          linux_servers.{{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in config.simulation.items() %}
          simulation.{{ key }}: "{{ value }}",
{% endfor %}
{% for key, value in config.splunk_server.items() %}
          splunk_server.{{ key }}: "{{ value }}",
{% endfor %}
        }
    end
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "{{ server.hostname }}"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end