VM_NAME= "Windows-2016-DC"
Vagrant.configure("2") do |config|

  config.vm.define "dc" do |cfg|
    cfg.vm.box = "d1vious/windows2016"
    cfg.vm.hostname = "#{VM_NAME}"
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "10.0.0.5", gateway: "10.0.0.1"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/playbooks/windows_dc.yml"
        ansible.config_file = "../ansible/ansible.config"
        ansible.compatibility_mode = "2.0"
    end


    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME}"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 3072]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
