config.vm.define "attack-range-splunk-server" do |config|
  VM_NAME= "attack-range-splunk-server"
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "#{VM_NAME}"
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest: 8000, host: 8000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8089, host: 8089, protocol: "tcp"
  config.vm.network :private_network, ip: "{{ splunk_server_private_ip }}"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbooks/splunk_server.yml"
      ansible.config_file = "../ansible/ansible.cfg"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3",
        splunk_admin_password: '{{ splunk_admin_password }}',
        splunk_url: '{{ splunk_url }}',
        splunk_binary: '{{ splunk_binary }}',
        s3_bucket_url: '{{ s3_bucket_url }}',
        splunk_escu_app: '{{ splunk_escu_app }}',
        splunk_asx_app: '{{ splunk_asx_app }}',
        splunk_windows_ta: '{{ splunk_windows_ta }}',
        splunk_cim_app: '{{ splunk_cim_app }}',
        splunk_sysmon_ta: '{{ splunk_sysmon_ta }}',
        caldera_password: '{{ caldera_password }}',
        splunk_mltk_app: '{{ splunk_mltk_app }}',
        splunk_bots_dataset: '{{ splunk_bots_dataset }}',
        splunk_stream_app: '{{ splunk_stream_app }}',
        splunk_python_app: '{{ splunk_python_app }}',
        install_es: '{{ install_es }}',
        install_mltk: '{{ install_mltk }}',
        splunk_es_app: '{{ splunk_es_app }}',
        phantom_app: '{{ phantom_app }}',
        phantom_server: '{{ phantom_server }}',
        phantom_server_private_ip: '{{ phantom_server_private_ip }}',
        phantom_admin_password: '{{ phantom_admin_password }}',
        splunk_security_essentials_app: '{{ splunk_security_essentials_app }}',
        punchard_custom_visualization: '{{ punchard_custom_visualization }}',
        status_indicator_custom_visualization: '{{ status_indicator_custom_visualization }}',
        splunk_attack_range_dashboard: '{{ splunk_attack_range_dashboard }}',
        timeline_custom_visualization: '{{ timeline_custom_visualization }}',
        install_mission_control: '{{ install_mission_control }}',
        mission_control_app: '{{ mission_control_app }}',
        install_dsp: '{{ install_dsp }}',
        dsp_client_cert_path: '{{ dsp_client_cert_path }}',
        dsp_node: '{{ dsp_node }}',
        splunk_server_private_ip: '{{ splunk_server_private_ip }}',
        cloud_attack_range: '0'
      }
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui = true
    vb.name = "#{VM_NAME}"
    vb.customize ["modifyvm", :id, "--memory", 6144]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end
end
