# Wireguard client config for client1

[Interface]
Address = 10.0.1.11/32
PrivateKey = +PQOZitg3llwMy9owxvI+Gvpqurqf/dHKCojexsWvHg=
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = mtwP8RuqUZYxeRxVVCiapW8vTSwt7k9waISILfMoqiA=
AllowedIPs = 10.0.1.0/24, 10.0.2.0/24
Endpoint = 3.9.114.127:51820
